set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U2 [get_ports {out[2]}]
set_property PACKAGE_PIN U4 [get_ports {out[1]}]
set_property PACKAGE_PIN V4 [get_ports {out[0]}]
set_property PACKAGE_PIN W4 [get_ports {out[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {Display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[0]}]
set_property PACKAGE_PIN W6 [get_ports {Display[5]}]
set_property PACKAGE_PIN U8 [get_ports {Display[4]}]
set_property PACKAGE_PIN V8 [get_ports {Display[3]}]
set_property PACKAGE_PIN U5 [get_ports {Display[2]}]
set_property PACKAGE_PIN V5 [get_ports {Display[1]}]
set_property PACKAGE_PIN U7 [get_ports {Display[0]}]


set_property PACKAGE_PIN W7 [get_ports {Display[6]}]
set_property PACKAGE_PIN L1 [get_ports ledtest]
set_property IOSTANDARD LVCMOS33 [get_ports ledtest]

set_property PACKAGE_PIN T17 [get_ports minplus]
set_property IOSTANDARD LVCMOS33 [get_ports minplus]
set_property PACKAGE_PIN E19 [get_ports plustest]
set_property IOSTANDARD LVCMOS33 [get_ports plustest]
set_property PACKAGE_PIN W19 [get_ports hrplus]
set_property IOSTANDARD LVCMOS33 [get_ports hrplus]